### ISSUE TITLE
use yarn to install dependencies

### ISSUE THREAD

**Issue by Toddses** [TricomB2B/tricom-generator#10]
I think this might be added in the generator release 1.0.0 which presumably they are close to releasing. We should switch then.

**Comment by Toddses** [comment]
1.0.0 was released this weekend. Look into updating.

**Comment by Taylord93** [comment]
I know yeoman runs `npm install` by default, in order to have yeoman you must have node installed. Im worried that if we switch the initial install to yarn it may cause errors for some users. Perhaps we could just include a lockfile and encourage users to use yarn?

**Comment by Taylord93** [comment]
After in person discussion decided to stick to yarn. PR #13
