### ISSUE TITLE
.editorconfig

### ISSUE THREAD

**Issue by Toddses** [TricomB2B/tricom-generator#20]
I'm finding that using `indent_style = tab` is pretty frustrating for getting matching format betwixt us. This is because tab spacing is obviously set differently in each of our editors. I've also noticed that when reviewing code on GitHub, the formatting is frequently wonky.

I'd like to switch to `indent_style = space`, at the very least for JavaScript files, so that this can be standardized betwixt us. Ideally this would resolve formatting issues across the board.

**Comment by Toddses** [comment]
alright i think i have a better understanding of the purpose of tabs over spaces and i've adjusted my editor so hopefully we won't see any more fucked up file formatting. if we do i'll gladly resolve.

**Comment by Toddses** [comment]
i've read some good reasons to use tabs, and some to use spaces. so i'm not sure how i'm feeling on this at the moment.

**Comment by Toddses** [comment]
okay apparently this debate is a holy war that's been going on for years. i can't really get into it. there's no really good or obvious answer.

i'm voting spaces for our standard across the board because it's more predictable and in general mixing spaces and tabs seems to be the one thing everyone agrees on _not_ doing. at least with spaces, our formatting is guaranteed to look well formatted in all IDEs, as well as on github. and since we minify everything, the idea that tabs over spaces is going to save on filesize is basically moot.

on top of all that, most prominent developers and open source projects are using 2 spaces (this includes yeoman, angular, sass, and many more) so I'm pretty satisfied with standardizing 2 spaces instead of tabs.

I can't believe I spent time today trying to decide between tabs and spaces.

@Taylord93 close this issue when you are prepared to succumb to spaces.

**Comment by Taylord93** [comment]
Im fine with either honestly because all of the Jetbrains IDE's use the tab button for whatever you have it configured to. *However*, if that were not the case I don't know why anyone would use spaces when you only have to hit a tab button once. But thats an argument for the slack channel...
