### ISSUE TITLE
consider using 'vm' as a standard controllerAs

### ISSUE THREAD

**Issue by Toddses** [TricomB2B/tricom-generator#5]
Considered best practice from Angular 1 as well as Angular 2 best practices.

Pros:
* Standardizes the controllerAs syntax
* Easier to remember throughout the application (you won't be looking up the correct variable, you always just know it)
* Considered best practice by the Angular team.
* More predictable behavior from the generator.

Cons:
* You could argue it's confusing to litter the app with 'vm'.

**Comment by Taylord93** [comment]
Im impartial. If this is a major thing for you feel free to put in a PR. Perhaps we could just offer an option to make the `controllerAs` a custom name?

**Comment by Toddses** [comment]
I like that idea. I'm for the `vm` largely because it's considered Angular best practice (including by the angular team). But I think making it an option is a good compromise.

**Comment by Taylord93** [comment]
Ill add it in to the next PR.
