### ISSUE TITLE
utilize generator to pull in tricom components

### ISSUE THREAD

**Issue by Toddses** [TricomB2B/tricom-generator#9]
I've been toying with ideas on how to pull in custom components that we've created (like `markable-click`) into a project. I created an organization, ngTricomB2B, for housing and organizing these repos, so they can be versioned separately, which I think would be ideal. You could pull in only the components you want and they can be managed separately from the generator codebase (and easily updated).

I am thinking we could hook into the generator to do this. I imagine a command like

```sh
$ yo tricom:component tcom-markable-click
tcom-markable-click installed in /src/components
```

I would love to install the component into the appropriate directory (eg `/src/directives` or `/src/factories`) but that may be difficult. I suppose it could work like

```sh
$ yo tricom:component tcom-markable-click -d directives
tcom-markable-click installed in /src/directives
```

The idea here is to pull the code directly from the repo via yeoman.

Thoughts?

**Comment by Toddses** [comment]
I guess importing a repo via yeoman is deprecated functionality. They created a package with the legacy code to handle this but it might be worth considering that it would stop being support at some point.

**Comment by Toddses** [comment]
We can maybe implement our own download method. I'm researching.

**Comment by Taylord93** [comment]
Im up for making something. I dont know if yeoman offers flags though (i.e. `yo tricom:component tcom-markable-click -d directives`), so we will have to figure out a better way of doing that.

**Comment by Toddses** [comment]
Check out my open PR. I've made a first pass which seems to work pretty well. #11

**Comment by Toddses** [comment]
I'll close this and we can continue discussion in the PR.
